### ISSUE TITLE
Stops working

### ISSUE THREAD

**Issue by RWissenburg** [XattSPT/com.moodo#1]
Hi there,

After adding my moodo to the app its working great, but after a day it stops working. a restart off the app wont work.

Only solution is to remove the moodo from homey and instaling it again, after that its working again  for about a day, then again it stops.

**Comment by XattSPT** [comment]
It seems a problem refreshing token. I’ve detected it and I hope to solve soon. Thank you for reporting!

**Comment by XattSPT** [comment]
Hi,

You are true. I’ve solved it and I hope to upload new version in a couple
of days. I’m finishing tests.

Thanks for your report.



El dg, 15 set 2019 a les 20:33 Oy1974 <notifications@github.com> va
escriure:

**Comment by RWissenburg** [comment]
Great, i wait and gonna test it when its updated. 👍

Op za 9 nov. 2019 om 18:13 schreef Gerard Ricart <notifications@github.com>:
