### ISSUE TITLE
Adding new Moodo isnt possible anymore - Device name empty

### ISSUE THREAD

**Issue by mruiter** [XattSPT/com.moodo#2]
Adding new moodo's as a device 2 homey isnt possible anymore.

When adding and after entering youre credentials you will get a list of moodo's 

The list fills but all names are empty

Also when you select one and click next for the add you will get a failed error because the Device.name is empty

SQLITE_CONSTRAINT: NOT NULL
contraint failed: Device.name

**Comment by XattSPT** [comment]
I'll will take a look on that...

please double check you enter a correct user/password. If not it shows empty devices (known bug)

**Comment by mruiter** [comment]
Yes that was the case now it fills the names . Will remember that bug for next time .

Thx for you’re quick reply and great app

Happy new year

**Comment by XattSPT** [comment]
I'll try to solve that. 

In a few days I'll be publishing an update where essence could be selected using Flowcards. I'll try to solve login issues also. 

Thanks for your support!
